// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.custom;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;

import java.net.URI;
import java.util.Objects;

/**
 * SaveResponse object
 */
public class ShortVideoCreateResponse implements Validable {
    /**
     * Video access key
     */
    @SerializedName("access_key")
    private String accessKey;


    /**
     * Video owner ID
     */
    @SerializedName("owner_id")
    private Integer ownerId;


    /**
     * URL for the video uploading
     */
    @SerializedName("upload_url")
    private URI uploadUrl;

    /**
     * Video ID
     */
    @SerializedName("video_id")
    private Integer videoId;

    public String getAccessKey() {
        return accessKey;
    }

    public ShortVideoCreateResponse setAccessKey(String accessKey) {
        this.accessKey = accessKey;
        return this;
    }

    public Integer getOwnerId() {
        return ownerId;
    }

    public ShortVideoCreateResponse setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
        return this;
    }

    public URI getUploadUrl() {
        return uploadUrl;
    }

    public ShortVideoCreateResponse setUploadUrl(URI uploadUrl) {
        this.uploadUrl = uploadUrl;
        return this;
    }

    public Integer getVideoId() {
        return videoId;
    }

    public ShortVideoCreateResponse setVideoId(Integer videoId) {
        this.videoId = videoId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(uploadUrl, accessKey, videoId, ownerId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ShortVideoCreateResponse saveResponse = (ShortVideoCreateResponse) o;
        return Objects.equals(ownerId, saveResponse.ownerId) &&
                Objects.equals(accessKey, saveResponse.accessKey) &&
                Objects.equals(uploadUrl, saveResponse.uploadUrl) &&
                Objects.equals(videoId, saveResponse.videoId);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("SaveResponse{");
        sb.append("ownerId=").append(ownerId);
        sb.append(", accessKey='").append(accessKey).append("'");
        sb.append(", uploadUrl=").append(uploadUrl);
        sb.append(", videoId=").append(videoId);
        sb.append('}');
        return sb.toString();
    }
}
